---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Длина никнейма должна быть от 3 до 16 символов включительно
  - Никнейм должен содержать латинские буквы, цифры или подчеркивания и начинаться только с латинской буквы
  - Имейл должен проверяться на корректность
  - Длина пароля должна быть от 6 до 16 символов включительно
  - Пароль должен содержать минимум 1 спецсимвол
  - Пользователь должен иметь возможность аутентифицироваться на сайте по имейлу и паролю
  - Пользователь должен иметь возможность аутентифицироваться на сайте по аккаунту GitHub
  - Пользователь должен иметь возможность аутентифицироваться на сайте по аккаунту Discord
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность выйти из аккаунта
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность просматривать рейтинг
  - Пользователь должен иметь возможность фильтровать рейтинг
  - Пользователь должен иметь возможность создавать новую игру
  - Пользователь должен иметь возможность присоединяться к созданной другим пользователем игре
  - Пользователь должен иметь возможность смотреть за игрой других пользователей
  - Пользователь должен иметь возможность создавать турнир
  - Пользователь должен иметь возможность принимать участие в созданных другими пользователями турнирах
  - Пользователь должен иметь возможность создавать задачи
  - Пользователь должен иметь возможность принимать участие в решении созданных другими пользователями задач
  - Пользователь должен иметь возможность просматривать список кланов
  - Пользователь должен иметь возможность при создании игры выбирать уровень заданий
  - Пользователь должен иметь возможность при создании игры выбирать тип соперника - другой пользователь, бот или друг
  - Пользователь должен иметь возможность при создании игры выбирать соперника из зарегистрированных на сайте пользователей
  - Пользователь должен иметь возможность при создании игры устанавливать время раунда - от 3 до 60 минут включительно
  - Пользователь должен иметь возможность при создании игры выбирать задание - рандом или конкретное из списка
  - Пользователь должен иметь возможность при создании игры выбирать задание по тегу
  - Пользователь должен иметь возможность во время игры отправлять сообщения в чате
  - Пользователь должен иметь возможность во время игры выбрать язык в описании задания - английский или русский
  - Пользователь должен иметь возможность во время игры выбирать язык программирования
  - Пользователь должен иметь возможность во время игры вводить код в редакторе
  - Пользователь должен иметь возможность во время игры запускать написанный код на выполнение
  - Пользователь должен иметь возможность во время игры сбросить решение
  - Пользователь должен иметь возможность во время игры закончить ее досрочно и сдасться
  - Пользователь должен иметь возможность узнать результат игры
  - Пользователь должен иметь возможность написать разработчикам о найденной ошибке
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать 1000 одновременных пользователей
implicit:
  - Пользователь должен иметь возможность смены языка интерфейса на главной странице
